[core][ndarray]: Fix: Missing `index_type_list` in `NDArray.__getitem__`
Caused by:
```
ValueError: Number of dimensions must be positive, got 0. Provide at least one shape dimension. [at NDArrayShape.__init__(shape: List[Int])]
```
on
```
print(array[0, 0])
```

Additionally added a TODO since the error message was otherwise extremely vague.